// <auto-generated />
using System;
using EAgenda.WebApp.Compartilhado.Infra.Orm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EAgenda.WebApp.Compartilhado.Infra.Orm.Migrations
{
    [DbContext(typeof(EAgendaDbContext))]
    [Migration("20260707181458_Add_TBDespesa")]
    partial class Add_TBDespesa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EAgenda.WebApp.Modulos.ModuloCategoria.Dominio.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_TBCategoria");

                    b.HasIndex("Titulo")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBCategoria_Titulo");

                    b.ToTable("TBCategoria", (string)null);
                });

            modelBuilder.Entity("EAgenda.WebApp.Modulos.ModuloCompromisso.Dominio.Compromisso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ContatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraTermino")
                        .HasColumnType("time");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Local")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_TBCompromisso");

                    b.HasIndex("ContatoId");

                    b.ToTable("TBCompromisso", (string)null);
                });

            modelBuilder.Entity("EAgenda.WebApp.Modulos.ModuloContato.Dominio.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_TBContato");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBContato_Email");

                    b.HasIndex("Telefone")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBContato_Telefone");

                    b.ToTable("TBContato", (string)null);
                });

            modelBuilder.Entity("EAgenda.WebApp.Modulos.ModuloDespesa.Dominio.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK_TBDespesa");

                    b.ToTable("TBDespesa", (string)null);
                });

            modelBuilder.Entity("TBDespesaCategoria", b =>
                {
                    b.Property<Guid>("CategoriasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DespesasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriasId", "DespesasId");

                    b.HasIndex("DespesasId");

                    b.ToTable("TBDespesaCategoria");
                });

            modelBuilder.Entity("EAgenda.WebApp.Modulos.ModuloCompromisso.Dominio.Compromisso", b =>
                {
                    b.HasOne("EAgenda.WebApp.Modulos.ModuloContato.Dominio.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_TBCompromisso_TBContato");

                    b.Navigation("Contato");
                });

            modelBuilder.Entity("TBDespesaCategoria", b =>
                {
                    b.HasOne("EAgenda.WebApp.Modulos.ModuloCategoria.Dominio.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAgenda.WebApp.Modulos.ModuloDespesa.Dominio.Despesa", null)
                        .WithMany()
                        .HasForeignKey("DespesasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
